/* Generated by tools/gfx.py - do not edit. */
#ifndef GFX_DATA_H
#define GFX_DATA_H

#include "gba.h"

#define TILE_GRASS1 0
#define TILE_GRASS2 1
#define TILE_GRASS3 2
#define TILE_PATH1 3
#define TILE_PATH2 4
#define TILE_WATER1 5
#define TILE_WATER2 6
#define TILE_TREE_TL 7
#define TILE_TREE_TR 8
#define TILE_TREE_BL 9
#define TILE_TREE_BR 10
#define TILE_FLOWER 11
#define TILE_WALL 12
#define TILE_ROOF 13
#define TILE_DOOR 14
#define TILE_WINDOW 15
#define TILE_SIGN 16
#define TILE_BERRY 17
#define TILE_BLACK 18
#define TILE_FLOOR 19
#define TILE_IWALL 20

#define TILE_COUNT 21
#define TILE_FONT_BASE 21
#define FONT_GLYPHS 47
#define HERO_FRAMES 8

extern const u16 gfx_bg_pal[16];
extern const u16 gfx_obj_pal[16];
extern const u16 gfx_bg_tiles[];
extern const u16 gfx_font_tiles[];
extern const u16 gfx_hero[];
extern const u8  gfx_char_map[128];

#endif
