/* Generated by tools/gfx.py - do not edit. */
#ifndef MAP_DATA_H
#define MAP_DATA_H

#include "gba.h"

#define MAP_TOWN 0
#define MAP_HOUSE 1

#define MAP_COUNT 2
#define BERRY_TOTAL 6

extern const u8 gfx_maps[MAP_COUNT][4096];

#endif
