FROM node:22-alpine AS base
WORKDIR /app

COPY client/package.json shared/package.json ./
RUN npm install

COPY client/ ./client/
COPY shared/ ./shared/

EXPOSE 5173
CMD ["npx", "vite", "--host", "0.0.0.0", "--config", "client/vite.config.ts", "client"]
